### ISSUE TITLE
Rwanda's 6th National Report

### ISSUE THREAD

**Issue by coeb1** [coeb1/Projects-management#20]
@samKanyamibwa is finalising Rwanda's 6NR to CBD and has invited CoEB team to write up the section on Target 19.

@Mattyc84  to create a Google Doc with suggested headings. (done – link sent)-----Done:

**Link to google doc:** 
https://docs.google.com/document/d/1_mRQP-ogyt8xH09ymGmZs_ZK3shgs2473a55z6Y6LHI/edit?ts=5f280e47

Team and Matt to produce the first draft by Friday 7th August

@bakaplin @DanielIgirimbabazi @Thacien1 @Deborahcyu @mmindje

**Comment by DanielIgirimbabazi** [comment]
> @samKanyamibwa is finalising Rwanda's 6NR to CBD and has invited CoEB team to write up the section on Target 19.
> 
> @Mattyc84 to create a Google Doc with suggested headings. (done – link sent)-----Done:
> 
> **Link to google doc:**
> https://docs.google.com/document/d/1_mRQP-ogyt8xH09ymGmZs_ZK3shgs2473a55z6Y6LHI/edit?ts=5f280e47
> 
> Team and Matt to produce the first draft by Friday 7th August
> 
> @bakaplin @DanielIgirimbabazi @Thacien1 @Deborahcyu @mmindje

Thanks for creating this ticket, we should get going with it as soon as possible, preferably tomorrow. Let's discuss about timing in our WhatsApp group.

**Comment by coeb1** [comment]
@Mattyc84 and @bakaplin  The Team has added its inputs to the report

Link [https://docs.google.com/document/d/1_mRQP-ogyt8xH09ymGmZs_ZK3shgs2473a55z6Y6LHI/edit?ts=5f280e47](url)

**Comment by Thacien1** [comment]
> @Mattyc84 and @bakaplin The Team has added its inputs to the report
> 
> Link [https://docs.google.com/document/d/1_mRQP-ogyt8xH09ymGmZs_ZK3shgs2473a55z6Y6LHI/edit?ts=5f280e47](url)

Hello BDMT, 
Can we meet tomorrow and work on Figures, tables of mobilized taxa? 
Thank you.

**Comment by mmindje** [comment]
> > @Mattyc84 and @bakaplin The Team has added its inputs to the report

https://docs.google.com/document/d/1_mRQP-ogyt8xH09ymGmZs_ZK3shgs2473a55z6Y6LHI/edit?ts=5f280e47
> 
> Hello BDMT,
> Can we meet tomorrow and work on Figures, tables of mobilized taxa?
> Thank you.

Thank you @Thacien1 for the proposal. @DanielIgirimbabazi @Deborahcyu 
Can we meet at  10:00 Am

if so, here is the meeting link: https://meet.google.com/uur-zrtf-emr
